#![allow(dead_code)]

//! Power-deficit recovery for already-planned service output.
//!
//! A deficit means the current tick's generated power plus service output cannot
//! cover housekeeping and active-service upkeep. Recovery cascades by shedding
//! active services from lowest gameplay priority first, clearing their pending
//! resource deltas so paused services do not still produce, and refunding upkeep
//! into the same tick's power pool. If enough services are shed, power returns
//! non-negative; otherwise the remaining shortfall is left visible in
//! `RunState.resources.power_available` for warnings and prestige checks.

use crate::game::sim::state::{catalog_service_order, RunState, ServicePauseReason};

#[derive(Debug, Clone, Copy, Default)]
/// Per-service resource changes staged by production before deficit recovery.
///
/// Entries are indexed to match `RunState.services`. Deficit handling clears an
/// entry when its service is paused, which prevents the later unlock/resource
/// phase from applying output that no longer has power behind it.
pub struct PendingServiceDelta {
    /// Effective service power upkeep reserved for this tick.
    pub power_upkeep: f32,
    /// Power generated by this service during this tick.
    pub power_output: f32,
    /// Net materials change to apply after deficit recovery.
    pub materials_delta: f32,
    /// Data produced after material throttling and multipliers.
    pub data_delta: f32,
    /// Survey progress produced after multipliers.
    pub survey_delta: f32,
}

impl PendingServiceDelta {
    /// Clears all staged output for a service paused by deficit recovery.
    ///
    /// This is the fallback behavior for a shed service: the service stays
    /// desired but contributes no power, materials, data, or survey progress to
    /// the remainder of the tick.
    pub fn clear(&mut self) {
        *self = Self::default();
    }
}

/// Cascades power shortfall recovery across active services.
///
/// Reads active-service priority, pending upkeep/output, and the Hardened Relays
/// refund ratio from `state`. Mutates service pause state, staged deltas, power
/// reservation/availability, and crew assignment. This runs after upkeep has
/// exposed the net shortfall and before resource/survey deltas are committed so
/// any shed service has its same-tick production removed.
pub fn resolve_power_deficit(state: &mut RunState, pending: &mut [PendingServiceDelta]) {
    if state.resources.power_available >= 0.0 {
        return;
    }

    let refund_ratio = state.hardened_relays_refund_ratio();
    let mut indices: Vec<usize> = state
        .services
        .iter()
        .enumerate()
        .filter(|(_, service)| service.is_active)
        .map(|(index, _)| index)
        .collect();

    indices.sort_by_key(|&index| {
        (
            std::cmp::Reverse(state.services[index].priority),
            std::cmp::Reverse(catalog_service_order(&state.services[index].service_id)),
        )
    });

    for index in indices {
        if state.resources.power_available >= 0.0 {
            break;
        }

        let service = &mut state.services[index];
        let service_pending = &mut pending[index];

        state.resources.power_available -= service_pending.power_output;
        state.resources.power_reserved -= service_pending.power_upkeep;
        state.resources.power_available += service_pending.power_upkeep;
        state.resources.power_available += service_pending.power_upkeep * refund_ratio;

        service.is_active = false;
        service.is_paused = true;
        service.pause_reason = Some(ServicePauseReason::Deficit);
        service.assigned_crew = 0;

        service_pending.clear();
    }

    let crew_assigned: u16 = state
        .services
        .iter()
        .filter(|service| service.is_active)
        .map(|service| service.assigned_crew as u16)
        .sum();

    state.resources.crew_assigned = crew_assigned.min(state.resources.crew_total as u16) as u8;
    state.resources.crew_available = state
        .resources
        .crew_total
        .saturating_sub(state.resources.crew_assigned);
}
