//! Static data catalog for operational doctrines.
//!
//! These definitions are read-only once loaded at startup; they are never mutated at runtime.
//! See [`crate::game::sim::state::RunState`] for the mutable game state that consumes this data.

use super::services::SURVEY_UPLINK_ID;
use super::systems::REACTOR_CORE_ID;

/// Stable string ID for the "Efficient Shifts" doctrine.
pub const EFFICIENT_SHIFTS_ID: &str = "efficient-shifts";
/// Stable string ID for the "Deep Survey Protocols" doctrine.
pub const DEEP_SURVEY_PROTOCOLS_ID: &str = "deep-survey-protocols";
/// Stable string ID for the "Hardened Relays" doctrine.
pub const HARDENED_RELAYS_ID: &str = "hardened-relays";
/// Stable string ID for the "Frontier Charters" doctrine.
pub const FRONTIER_CHARTERS_ID: &str = "frontier-charters";

/// The gameplay effect applied when a doctrine is active.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DoctrineEffect {
    /// Reduces crew cost of the first support service by `reduction`, down to `minimum_crew`.
    FirstSupportServiceCrewDiscount { reduction: u8, minimum_crew: u8 },
    /// Multiplies survey progress generated by the named service by `multiplier`.
    SurveyProgressMultiplier {
        /// ID of the service whose survey output is scaled.
        source_service_id: &'static str,
        /// Multiplicative factor applied to survey progress (e.g. `1.20` = +20%).
        multiplier: f32,
    },
    /// Refunds a fraction of the current-tick power upkeep when a service is disabled in the same tick.
    SameTickPowerRefundOnDisable { refund_ratio: f32 },
    /// Newly discovered planets begin at the given level for the named system.
    NewlyDiscoveredPlanetsStartWithSystemLevel { system_id: &'static str, level: u8 },
}

/// Defines a single choosable doctrine that modifies station behaviour for the run.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DoctrineDefinition {
    /// Unique kebab-case identifier referenced by [`crate::game::sim::state::RunState`].
    pub id: &'static str,
    /// Short display name shown in the UI.
    pub label: &'static str,
    /// Human-readable summary of the effect shown in the doctrine picker.
    pub description: &'static str,
    /// The concrete gameplay effect applied while this doctrine is active.
    pub effect: DoctrineEffect,
}

/// Ordered catalog of all available doctrines; index is not a stable ID — use `id` field for lookups.
pub const DOCTRINES: &[DoctrineDefinition] = &[
    DoctrineDefinition {
        id: EFFICIENT_SHIFTS_ID,
        label: "Efficient Shifts",
        description: "The first support service needs 1 less Crew, to a minimum of 1.",
        effect: DoctrineEffect::FirstSupportServiceCrewDiscount {
            reduction: 1,
            minimum_crew: 1,
        },
    },
    DoctrineDefinition {
        id: DEEP_SURVEY_PROTOCOLS_ID,
        label: "Deep Survey Protocols",
        description: "Survey Uplink grants 20% more survey progress.",
        effect: DoctrineEffect::SurveyProgressMultiplier {
            source_service_id: SURVEY_UPLINK_ID,
            multiplier: 1.20,
        },
    },
    DoctrineDefinition {
        id: HARDENED_RELAYS_ID,
        label: "Hardened Relays",
        description: "Disabled services refund 50% of current-tick power upkeep back to the same tick.",
        effect: DoctrineEffect::SameTickPowerRefundOnDisable { refund_ratio: 0.50 },
    },
    DoctrineDefinition {
        id: FRONTIER_CHARTERS_ID,
        label: "Frontier Charters",
        description: "Newly discovered planets begin with Reactor Core level 2.",
        effect: DoctrineEffect::NewlyDiscoveredPlanetsStartWithSystemLevel {
            system_id: REACTOR_CORE_ID,
            level: 2,
        },
    },
];

/// Looks up a doctrine definition by its stable string ID. Returns `None` if not found.
pub fn doctrine_by_id(id: &str) -> Option<&'static DoctrineDefinition> {
    DOCTRINES.iter().find(|doctrine| doctrine.id == id)
}

/// Returns a doctrine definition by ID, panicking if not found.
///
/// # Panics
/// Panics with "doctrine must exist in catalog" if the ID is not found.
#[track_caller]
pub fn doctrine_by_id_required(id: &str) -> &'static DoctrineDefinition {
    doctrine_by_id(id).expect("doctrine must exist in catalog")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_catalogs_doctrine_ids_exist() {
        assert_eq!(DOCTRINES.len(), 4);
        for id in [
            EFFICIENT_SHIFTS_ID,
            DEEP_SURVEY_PROTOCOLS_ID,
            HARDENED_RELAYS_ID,
            FRONTIER_CHARTERS_ID,
        ] {
            assert!(doctrine_by_id(id).is_some(), "missing doctrine: {id}");
        }
    }

    #[test]
    fn content_catalogs_doctrine_effects_match_plan() {
        assert_eq!(
            doctrine_by_id(EFFICIENT_SHIFTS_ID).unwrap().effect,
            DoctrineEffect::FirstSupportServiceCrewDiscount {
                reduction: 1,
                minimum_crew: 1,
            }
        );
        assert_eq!(
            doctrine_by_id(DEEP_SURVEY_PROTOCOLS_ID).unwrap().effect,
            DoctrineEffect::SurveyProgressMultiplier {
                source_service_id: SURVEY_UPLINK_ID,
                multiplier: 1.20,
            }
        );
        assert_eq!(
            doctrine_by_id(HARDENED_RELAYS_ID).unwrap().effect,
            DoctrineEffect::SameTickPowerRefundOnDisable { refund_ratio: 0.50 }
        );
        assert_eq!(
            doctrine_by_id(FRONTIER_CHARTERS_ID).unwrap().effect,
            DoctrineEffect::NewlyDiscoveredPlanetsStartWithSystemLevel {
                system_id: REACTOR_CORE_ID,
                level: 2,
            }
        );
    }

    #[test]
    #[should_panic(expected = "doctrine must exist in catalog")]
    fn doctrine_by_id_required_panics_on_unknown() {
        doctrine_by_id_required("nonexistent-doctrine-that-does-not-exist");
    }
}
